### ISSUE TITLE
Bot is still stuck

### ISSUE THREAD

**Issue by prayzcs** [hrt/AimRite#33]
Im having the same problem as the guy had mentioned before. The Bot is stuck at the same point altough I have selected Iva before going into playground. I have done everything exactly like you instructed us to do but its still stuck and not doing any aimbot.
![screenshot_537](https://user-images.githubusercontent.com/21335420/50384253-c7fa4300-06c2-11e9-954c-3aaa690d6758.png)
![screenshot_57](https://user-images.githubusercontent.com/21335420/50384283-114a9280-06c3-11e9-8aa6-ab32a70474a9.png)

**Comment by hrt** [comment]
Yeah I don't really update this anymore mate, sorry
